name: Feminine1st
favicon: null
layout_spectrum: 0.8011932170484215
typography_spectrum: 0.4820411638356745
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.4089265172369778
  lightness: 0.965408593416214
  saturation: 0.4245922239497304
  rhythmicContrast: 0.6424902151338756
purpose: []
